[workspace]
members = [
    "bin/mev-rs",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-lib",
]
default-members = ["bin/mev-rs"]

[patch."https://github.com/ralexstokes/ethereum-consensus"]
ethereum-consensus = { git = "https://github.com/ralexstokes//ethereum-consensus", rev = "5531c285fc4030e265b8499612946d8a704e2c57" }

[patch."https://github.com/ralexstokes/ssz-rs"]
ssz-rs = { git = "https://github.com/ralexstokes//ssz-rs", rev = "5946af4a65a1e8547a8fc7cfb62e12637421b8f2" }

[patch."https://github.com/ralexstokes/beacon-api-client"]
beacon-api-client = { git = "https://github.com/ralexstokes//beacon-api-client", rev = "53690a711e33614d59d4d44fb09762b4699e2a4e" }
