[package]
name = "mev_boost_rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3.21"

axum = "0.5.4"
axum-json-rpc = { git = "https://github.com/ralexstokes/axum-json-rpc" }
ethers-providers = "0.6.2"
url = { version = "2.2.2", default-features = false }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"

thiserror = "1.0.30"

clap = { version = "3.1.14", features = ["derive"] }

[[bin]]
name = "main"
