[package]
name = "mev-boost-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3.21"

axum = "0.5.4"
url = { version = "2.2.2", default-features = false }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"

thiserror = "1.0.30"

clap = { version = "3.1.14", features = ["derive"] }

ethereum_consensus = { git = "https://github.com/ralexstokes/ethereum_consensus" }
ssz_rs = { git = "https://github.com/ralexstokes/ssz_rs" }
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client" }

[dev-dependencies]
rand = "0.8.5"

[[bin]]
name = "main"
