[workspace]
resolver = "2"
members = ["bin/mev", "mev-boost-rs", "mev-relay-rs", "mev-build-rs", "mev-rs"]
default-members = ["bin/mev"]

[workspace.dependencies]
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "56418ea" }
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client", rev = "56a290c" }
ssz_rs = "0.9.0"
